AWSTemplateFormatVersion: "2010-09-09"
Description: creating the vpc
#correct

Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "vpc"
        Parameters: 
          - VpcCIDR
      - 
        Label: 
          default: "subnet"
        Parameters: 
          - subnetCIDR

Parameters:
  VpcCIDR:
    Type: String
    Default: 10.0.0.0/16
    Description: creating the vpc
  subnetCIDR:
    Type: String
    Default: 10.0.0.0/24
    Description: created the vpc
#creating the vpc
Resources:
  mynewVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock:
        Ref: VpcCIDR
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      InstanceTenancy: "default"
      Tags:
      - Key: stack
        Value: Do

#creating the internet gateway
  myInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: rs
        Value: rudraig  

#attach the internet gateway  
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: mynewVPC
      InternetGatewayId:
        Ref: myInternetGateway

#creating the public subnet
  mypublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: mynewVPC
      CidrBlock: 
        Ref: subnetCIDR
      AvailabilityZone: "us-east-1a"
      Tags:
      - Key: mama
        Value: rudrapublic  
#creating the routetable
  myRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  
        Ref: mynewVPC
      Tags:
      - Key: mama
        Value: rudrart
#add the routes to the routetable
  myRoute:
    Type: AWS::EC2::Route
    Properties:
       RouteTableId:
         Ref: myRouteTable
       DestinationCidrBlock: 0.0.0.0/0
       GatewayId:
         Ref: myInternetGateway  

#   association of subnet to the routetable
  mySubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: mypublicSubnet
      RouteTableId:
        Ref: myRouteTable
# creating the securitygroup and port number
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      GroupName: "soo"
      VpcId: 
        Ref: mynewVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

# creating the ec2 instances  
  myec2instances:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-069aabeee6f53e7bf"
      InstanceType: "t2.micro"
      KeyName: "rudrasoma"
      SubnetId:
        Ref: mypublicSubnet 
      SecurityGroupIds:
        - Ref: "InstanceSecurityGroup"
      Tags:
       - Key: haa
         Value: loud   
# creating the volume for the ec2 instances
  myVolume:
    Type: AWS::EC2::Volume
    Properties:
      Size: 98
      AvailabilityZone: "us-east-1a" 
      VolumeType: gp2
      Tags:
        - Key: qq
          Value: mamavolume
# creating the keypair to the instance  
  NewKeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: rudrasoma

  

Outputs:
[10:40 am, 17/04/2023] Child🤪: hi
[10:41 am, 17/04/2023] Child🤪: AWSTemplateFormatVersion: "2010-09-09"

Description: creating the vpc
#correct

Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "vpc"
        Parameters: 
          - VpcCIDR
      - 
        Label: 
          default: "subnet"
        Parameters: 
          - subnetCIDR

Parameters:
  VpcCIDR:
    Type: String
    Default: 10.0.0.0/16
    Description: creating the vpc
  subnetCIDR:
    Type: String
    Default: 10.0.0.0/24
    Description: created the vpc
#creating the vpc
Resources:
  mynewVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock:
        Ref: VpcCIDR
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      InstanceTenancy: "default"
      Tags:
      - Key: stack
        Value: Do

#creating the internet gateway
  myInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: rs
        Value: rudraig  

#attach the internet gateway  
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: mynewVPC
      InternetGatewayId:
        Ref: myInternetGateway

#creating the public subnet
  mypublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: mynewVPC
      CidrBlock: 
        Ref: subnetCIDR
      AvailabilityZone: "us-east-1a"
      Tags:
      - Key: mama
        Value: rudrapublic  
#creating the routetable
  myRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  
        Ref: mynewVPC
      Tags:
      - Key: mama
        Value: rudrart
#add the routes to the routetable
  myRoute:
    Type: AWS::EC2::Route
    Properties:
       RouteTableId:
         Ref: myRouteTable
       DestinationCidrBlock: 0.0.0.0/0
       GatewayId:
         Ref: myInternetGateway  

#   association of subnet to the routetable
  mySubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: mypublicSubnet
      RouteTableId:
        Ref: myRouteTable
# creating the securitygroup and port number
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      GroupName: "soo"
      VpcId: 
        Ref: mynewVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

# creating the ec2 instances  
  myec2instances:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-069aabeee6f53e7bf"
      InstanceType: "t2.micro"
      KeyName: "rudrasoma"
      SubnetId:
        Ref: mypublicSubnet 
      SecurityGroupIds:
        - Ref: "InstanceSecurityGroup"
      Tags:
       - Key: haa
         Value: loud   
# creating the volume for the ec2 instances
  myVolume:
    Type: AWS::EC2::Volume
    Properties:
      Size: 98
      AvailabilityZone: "us-east-1a" 
      VolumeType: gp2
      Tags:
        - Key: qq
          Value: mamavolume
# creating the keypair to the instance  
  NewKeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: rudrasoma

  

Outputs:
# to get the ec2 instances id
  myec2instances:
    Description: The ID of the ec2 instances
    Value: 
      Ref: myec2instances  
    Export:
      Name: myec2instances

# to get the vpc id
  mynewVPC:
    Description: The ID of the vpc
    Value: 
      Ref: mynewVPC
    Export:
      Name: mynewVPC

# to get the internetgateway id
  myInternetGateway:
    Description: The ID of the Ig
    Value: 
      Ref: myInternetGateway
    Export:
      Name: myInternetGateway

#to get the routetable id
  myRouteTable:
    Description: The ID of the route
    Value: 
      Ref: myRouteTable
    Export:
      Name: myRouteTable

# to get the security group id
  InstanceSecurityGroup:
    Description: The ID of the security
    Value: 
      Ref: InstanceSecurityGroup
    Export:
      Name: InstanceSecurityGroup 

# to get the publicsubnet id
  mypublicSubnet: 
    Description: The ID of the subnet
    Value: 
      Ref: mypublicSubnet
    Export:
      Name: mypublicSubnet
# to get the voulume id
  myVolume:
    Description: The ID of the volume
    Value: 
      Ref: myVolume
    Export:
      Name: myVolume
# to get keypair id
  NewKeyPair:
    Description: The ID of the volume
    Value: 
      Ref: NewKeyPair
    Export:
      Name: NewKeyPair