AWSTemplateFormatVersion: "2010-09-09"
Resources:
  Parameters:
    Password:
      Type: String
      Description: Please enter a password 
      ConstraintDescription: Password must be between 8 and 32 characters, start with lowercase or uppercase letter, and can be alphanumeric with the following special characters !@#$%& 
      NoEcho: true
      AllowedPattern: ^[a-zA-Z][a-zA-Z0-9!@#$%&]{8,32}$
  MyCodeCommitRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: my-repo 
  
  MyUser:
    Type: "AWS::IAM::User"
    Properties:
      UserName: "myuser"

  MyUserPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "MyUserPolicy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "codecommit:*"
            Resource: "*"
      Users:
        Ref: MyUser
