AWSTemplateFormatVersion: "2010-09-09"
Description: Creating the codecommit
Resources:
  Parameters:
    Password:
      Type: String
      Description: Please enter a password 
      ConstraintDescription: Password must be between 8 and 32 characters, start with lowercase or uppercase letter, and can be alphanumeric with the following special characters !@#$%& 
      NoEcho: true
      AllowedPattern: ^[a-zA-Z][a-zA-Z0-9!@#$%&]{8,32}$

  mycodecommit:
    Type: AWS::CodeCommit::Repository
    Properties: 
      RepositoryDescription: Create the new codecommit
      RepositoryName: mycode
      Tags:
        - Key: "my"
          Value: "code"
  
  Ganga:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: 
          Ref: Ganga@005

  newonePolicytocodecommit:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: "codecommit"
      PolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: 
              - "codecommit:*"
            Resource: "*"
      Users:
        - Ref: Soma